version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
#  forestadmin:
#    build:
#      context: ./forestadmin
#      dockerfile: Dockerfile
#    container_name: forestadmin
#    command: "npm run dev"
#    volumes:
#      - ./forestadmin:/usr/src/app
#    environment:
#      - NODE_ENV=development
#      - APPLICATION_PORT=3310
#      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/postgres
#      - DATABASE_SCHEMA=public
#      - DATABASE_SSL=false
#      - FOREST_AUTH_SECRET=de521640b7032a38129b82ca6be65c72cc901430a0b61406d4403bfcb671e2a62ac5531d598151da3aa607cd3aa97f71
#      - FOREST_ENV_SECRET=e8337f94a1100f7677ae2c66e8793ac9b92fc88248790f6d721a5fb52995786a
#      - GOOGLE_APPLICATION_CREDENTIALS=./credentials/mvp-athleads-dev-9f4083b92641.json
#    ports:
#      - "3310:3310"
#    depends_on:
#      - "postgres"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./backend/hasura/migrations:/hasura-migrations
      - ./backend/hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES:
        startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
